"""add agent platform columns and memory table

Revision ID: 03241aac0f9f
Revises: a4f2c8d9e7b1
Create Date: 2026-03-17 08:34:46.387481

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03241aac0f9f"
down_revision: str | Sequence[str] | None = "a4f2c8d9e7b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_project_memory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "project_id",
            sa.UUID(),
            nullable=False,
            comment="One memory record per project",
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=True,
            comment="Agent-curated key decisions, patterns, preferences (~600 tokens max)",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_by_conversation_id",
            sa.UUID(),
            nullable=True,
            comment="Last conversation that updated this memory",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by_conversation_id"], ["ai_conversation.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.add_column(
        "ai_conversation",
        sa.Column(
            "summary",
            sa.Text(),
            nullable=True,
            comment="Rolling intra-session summary of older messages",
        ),
    )
    op.add_column(
        "ai_conversation",
        sa.Column(
            "status",
            sa.String(length=30),
            server_default="idle",
            nullable=False,
            comment="idle | awaiting_plan_approval | executing | awaiting_approval | interrupted",
        ),
    )
    op.add_column(
        "ai_conversation",
        sa.Column(
            "mode",
            sa.String(length=20),
            server_default="chat",
            nullable=False,
            comment="chat | proactive",
        ),
    )
    op.create_index(
        "idx_ai_conversation_status", "ai_conversation", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ai_conversation_status", table_name="ai_conversation")
    op.drop_column("ai_conversation", "mode")
    op.drop_column("ai_conversation", "status")
    op.drop_column("ai_conversation", "summary")
    op.drop_table("agent_project_memory")
    # ### end Alembic commands ###
