"""add_organization_tables

Revision ID: 30d06003cc31
Revises: 4b9d33f7724a
Create Date: 2026-02-13 05:03:08.110248

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30d06003cc31"
down_revision: str | Sequence[str] | None = "4b9d33f7724a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
            comment="URL-friendly identifier",
        ),
        sa.Column(
            "is_personal",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
            comment="True for auto-created personal orgs",
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Organization settings: defaults, preferences",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_organization_slug",
        "organization",
        ["slug"],
        unique=False,
        postgresql_where=sa.text("NOT is_deleted"),
    )
    op.create_index(op.f("ix_organization_slug"), "organization", ["slug"], unique=True)
    op.create_table(
        "organization_member",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="Organization role: owner, admin, member",
        ),
        sa.Column(
            "joined_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member')", name="check_org_member_role"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_organization_member_user"
        ),
    )
    op.create_index(
        "idx_org_member_org", "organization_member", ["organization_id"], unique=False
    )
    op.create_index(
        "idx_org_member_user", "organization_member", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_organization_member_organization_id"),
        "organization_member",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_member_user_id"),
        "organization_member",
        ["user_id"],
        unique=False,
    )
    op.add_column("project", sa.Column("organization_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_project_organization_id"), "project", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        None, "project", "organization", ["organization_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project", type_="foreignkey")
    op.drop_index(op.f("ix_project_organization_id"), table_name="project")
    op.drop_column("project", "organization_id")
    op.drop_index(
        op.f("ix_organization_member_user_id"), table_name="organization_member"
    )
    op.drop_index(
        op.f("ix_organization_member_organization_id"), table_name="organization_member"
    )
    op.drop_index("idx_org_member_user", table_name="organization_member")
    op.drop_index("idx_org_member_org", table_name="organization_member")
    op.drop_table("organization_member")
    op.drop_index(op.f("ix_organization_slug"), table_name="organization")
    op.drop_index(
        "idx_organization_slug",
        table_name="organization",
        postgresql_where=sa.text("NOT is_deleted"),
    )
    op.drop_table("organization")
    # ### end Alembic commands ###
