"""add_unique_partial_index_task_order

Revision ID: 4b9d33f7724a
Revises: a1b2c3d4e5f6
Create Date: 2026-02-09 23:53:27.154584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9d33f7724a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_task_project_order'), table_name='task', postgresql_where='(NOT is_deleted)')
    op.create_index('idx_task_project_order', 'task', ['project_id', 'order_index'], unique=True, postgresql_where=sa.text('NOT is_deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_project_order', table_name='task', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('idx_task_project_order'), 'task', ['project_id', 'order_index'], unique=False, postgresql_where='(NOT is_deleted)')
    # ### end Alembic commands ###
