"""add email_verification table

Revision ID: b6f3a6c8b4aa
Revises: 30d06003cc31
Create Date: 2026-02-19 21:23:13.268677

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6f3a6c8b4aa"
down_revision: str | Sequence[str] | None = "30d06003cc31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "token_hash",
            sa.String(length=255),
            nullable=False,
            comment="SHA-256 hash of verification token",
        ),
        sa.Column(
            "expires_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="Expiration (24 hours)",
        ),
        sa.Column(
            "used_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="When token was used",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "idx_email_verification_user", "email_verification", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_verification_user_id"),
        "email_verification",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_email_verification_user_id"), table_name="email_verification"
    )
    op.drop_index("idx_email_verification_user", table_name="email_verification")
    op.drop_table("email_verification")
    # ### end Alembic commands ###
